//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Astroturfs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Astroturfs()
        {
            this.Rezervations = new HashSet<Rezervations>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public string Tel { get; set; }
        public string Info { get; set; }
        public Nullable<int> County_ID { get; set; }
        public Nullable<int> Manager_ID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Counties Counties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervations> Rezervations { get; set; }
    }
}
