//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Campaign
    {
        public int ID { get; set; }
        [DisplayName("Kampanya Adý")]
        public string Name { get; set; }
        [DisplayName("Kampanya Bilgisi")]
        public string Info { get; set; }
    }
}
