//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HaliSahaDBEntities1 : DbContext
    {
        public HaliSahaDBEntities1()
            : base("name=HaliSahaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Astroturfs> Astroturfs { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Counties> Counties { get; set; }
        public virtual DbSet<Rezervations> Rezervations { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UserLogin> UserLogin { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Campaign> Campaign { get; set; }
    }
}
