//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervations
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool State { get; set; }
        public Nullable<int> Astroturf_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
    
        public virtual Astroturfs Astroturfs { get; set; }
        public virtual Users Users { get; set; }
    }
}
