//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Astroturfs = new HashSet<Astroturfs>();
            this.Rezervations = new HashSet<Rezervations>();
        }
    
        public int ID { get; set; }
        [DisplayName("Ad")]
        [Required]
        public string Name { get; set; }
        [DisplayName("Soyad")]
        [Required]
        public string LastName { get; set; }
        [DisplayName("Mail")]
        [Required]
        public string Mail { get; set; }
        [DisplayName("Telefon")]
        [Required]
        public string Tel { get; set; }
        [DisplayName("Kayýt Tarihi")]
        [Required]
        public System.DateTime RegisterDate { get; set; }
        [DisplayName("Puan")]
        [Required]
        public int Point { get; set; }
        [DisplayName("Rol")]
        [Required]
        public Nullable<int> Role_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Astroturfs> Astroturfs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervations> Rezervations { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual UserLogin UserLogin { get; set; }
    }
}
