//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int User_ID { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
